let S,me,selected;const $=s=>document.querySelector(s);async function api(u,o={}){let r=await fetch(u,{headers:{'Content-Type':'application/json'},...o}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Error');return d}const money=n=>'BDT '+Number(n).toLocaleString('en-BD');
async function init(){S=await api('/api/settings');me=(await api('/api/me')).user;$('#notice').textContent=S.notice;$('#heroTitle').textContent=S.heroTitle||'ফ্রী ফায়ার ডায়মন্ড টপআপ';$('#heroText').textContent=S.heroText||'দ্রুত, সহজ এবং নিরাপদে Diamond Top-Up করুন।';$('#bkash').textContent=S.bkash;$('#nagad').textContent=S.nagad;[['tg',S.supportTelegram],['group',S.supportGroup],['wa',S.supportWhatsApp],['ftg',S.supportTelegram],['fwa',S.supportWhatsApp]].forEach(([id,u])=>{$('#'+id).href=u});renderOffers();renderPackages();userUI()}
function renderOffers(){$('#offers').innerHTML=S.specialOffers.map(x=>`<article class="offer"><div class="pic">${x.image?'🖼️':'💎'}</div><div><b>${x.title}</b><br><small>${x.subtitle}</small></div></article>`).join('')}
function renderPackages(){$('#packages').innerHTML=S.offers.map((x,i)=>`<button class="pkg ${selected?.name===x.name?'sel':''}" onclick="pick(${i})"><b>${x.name}</b><span>${money(x.price)}</span></button>`).join('')}
function pick(i){selected=S.offers[i];renderPackages();$('#selected').textContent=selected.name;$('#price').textContent=money(selected.price);$('#order').scrollIntoView({behavior:'smooth',block:'center'})}
function userUI(){if(me){$('#user').textContent=me.id;$('#account').textContent='My Account'}else{$('#user').textContent='Login করে অর্ডার করুন';$('#account').textContent='Login'}}
function openModal(){if(me){showAccount()}else{authTab('login')}$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function authTab(t){$('#auth').classList.remove('hidden');$('#accountView').classList.add('hidden');$('#login').classList.toggle('hidden',t!=='login');$('#reg').classList.toggle('hidden',t!=='reg');$('#tl').classList.toggle('active',t==='login');$('#tr').classList.toggle('active',t==='reg')}
function showAccount(){$('#auth').classList.add('hidden');$('#accountView').classList.remove('hidden');$('#accountView').innerHTML=`<div class="account"><small>CUSTOMER ACCOUNT</small><h2>${me.name}</h2><div class="cid"><small>Customer ID</small><br><b>${me.id}</b><br>${me.email}</div><button onclick="orders()">My Orders</button><div id="olist"></div><button style="background:#eee;color:#444" onclick="logout()">Logout</button></div>`}
async function orders(){let a=await api('/api/orders');$('#olist').innerHTML=a.length?a.map(o=>`<div style="border:1px solid #eee;border-radius:9px;padding:10px;margin-top:7px"><b>#${o.serial} ${o.packageName}</b><br><small>UID: ${o.uid} · TrxID: ${o.trxId}</small><br>${money(o.price)} · ${o.status}</div>`).join(''):'<p>No orders yet.</p>'}
async function logout(){await api('/api/logout',{method:'POST'});me=null;closeModal();userUI()}
$('#account').onclick=openModal;$('#login').onsubmit=async e=>{e.preventDefault();try{me=(await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))})).user;closeModal();userUI();alert('Login সফল হয়েছে')}catch(x){$('#lm').textContent=x.message}};$('#reg').onsubmit=async e=>{e.preventDefault();try{me=(await api('/api/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))})).user;closeModal();userUI();alert('Account তৈরি হয়েছে: '+me.id)}catch(x){$('#rm').textContent=x.message}};
$('#order').onclick=async()=>{if(!me){openModal();alert('অর্ডার করতে Login প্রয়োজন');return}if(!selected)return alert('একটি প্যাকেজ নির্বাচন করুন');let uid=$('#uid').value.trim(),trx=$('#trx').value.trim();if(!uid||!trx)return alert('UID এবং Transaction ID দিন');try{let d=await api('/api/orders',{method:'POST',body:JSON.stringify({packageName:selected.name,price:selected.price,uid,trxId:trx,paymentMethod:$('#pay').value})});alert('অর্ডার সফল! Serial #'+d.order.serial);$('#uid').value='';$('#trx').value=''}catch(x){alert(x.message)}};async function copy(t){try{await navigator.clipboard.writeText(t);alert('কপি হয়েছে')}catch(e){alert(t)}}init();
